export const ACTIVITY_FEED_ITEM_SELECT = [
  'id',
  'org_id',
  'kind',
  'occurred_at',
  'created_at',
  'tab_key',
  'audience',
  'verb',
  'actor_profile_id',
  'refs',
  'group_key',
  'group_type',
  'is_collapsed',
  'sub_activity_count',
  'content',
  'summary',
  'preview',
  'action_button',
  'expanded_content',
  'importance',
  'is_read',
  'metadata',
  'created_by',
  'updated_at',
  'updated_by',
  'deleted_at',
  'deleted_by',
].join(',');

export const ACTIVITY_FEED_SECTION_SELECT = [
  'id',
  'org_id',
  'label',
  'created_at',
  'created_by',
  'updated_at',
  'updated_by',
  'deleted_at',
  'deleted_by',
].join(',');

export const ACTIVITY_FEED_GROUP_MEMBER_SELECT = [
  'id',
  'org_id',
  'group_id',
  'item_id',
  'created_at',
  'created_by',
  'updated_at',
  'updated_by',
  'deleted_at',
  'deleted_by',
].join(',');
