export const CLASS_SCHEDULE_SELECT = [
  'id',
  'org_id',
  'title',
  'description',
  'location',
  'meeting_link',
  'start_at',
  'end_at',
  'timezone',
  'status',
  'visibility',
  'theme_key',
  'source_kind',
  'source_learning_space_id',
  'source_channel_id',
  'source_session_id',
  'source_owner_user_id',
  'source_created_by_user_id',
  'source_related_learning_space_id',
  'created_at',
  'created_by',
  'updated_at',
  'updated_by',
  'deleted_at',
  'deleted_by',
].join(',');

export const CLASS_SCHEDULE_PARTICIPANT_SELECT = [
  'id',
  'org_id',
  'schedule_id',
  'profile_id',
  'role',
  'status',
  'display_name',
  'avatar_url',
  'theme_key',
  'created_at',
  'created_by',
  'updated_at',
  'updated_by',
  'deleted_at',
  'deleted_by',
].join(',');

export const CLASS_SCHEDULE_RECURRENCE_SELECT = [
  'id',
  'org_id',
  'schedule_id',
  'frequency',
  'interval',
  'by_weekday',
  'count',
  'until',
  'timezone',
  'created_at',
  'created_by',
  'updated_at',
  'updated_by',
  'deleted_at',
  'deleted_by',
].join(',');

export const CLASS_SCHEDULE_RECURRENCE_EXCEPTION_SELECT = [
  'id',
  'org_id',
  'recurrence_id',
  'occurrence_key',
  'reason',
  'created_at',
  'created_by',
  'updated_at',
  'updated_by',
  'deleted_at',
  'deleted_by',
].join(',');

export const CLASS_SCHEDULE_RECURRENCE_OVERRIDE_SELECT = [
  'id',
  'org_id',
  'recurrence_id',
  'occurrence_key',
  'patch',
  'created_at',
  'created_by',
  'updated_at',
  'updated_by',
  'deleted_at',
  'deleted_by',
].join(',');
